export const ADD__INDEGRIDENTS = "ADD__INDEGRIDENTS";
export const REMOVE__INDEGRIDENTS = "REMOVE__INDEGRIDENTS";
export const RESET__INDEGRIDENTS = "RESET__INDEGRIDENTS";

export const PLACE_ORDER_SUCESSFULLY = "PLACE_ORDER_SUCESSFULLY";
export const PLACE_ORDER_REJECTED = "PLACE_ORDER_REJECTED";
export const PLACING_ORDER_STARTED = "PLACING_ORDER_STARTED";  

export const FETCH_ORDER_SUCCESS = "FETCH_ORDER_SUCCESS";
export const FETCH_ORDER_FAILED = "FETCH_ORDER_FAILED";

export const AUTH__STARTED = "AUTH__STARTED";
export const AUTH__SUCCESS = "AUTH__SUCCESS";
export const AUTH__FAILED = "AUTH__FAILED";
export const AUTH__LOGOUT = "AUTH__LOGOUT";
export const AUTO__AUTH = "AUTO__AUTH";